# Generated by Django 2.1.7 on 2019-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0002_auto_20190312_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
